"""empty message

Revision ID: 3d0f65fb455f
Revises: 52894b0534ee
Create Date: 2022-05-30 21:37:30.588980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d0f65fb455f'
down_revision = '52894b0534ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('characters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('img', sa.String(length=120), nullable=False),
    sa.Column('height', sa.String(length=120), nullable=False),
    sa.Column('mass', sa.String(length=120), nullable=False),
    sa.Column('birth_year', sa.String(length=120), nullable=False),
    sa.Column('gender', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('birth_year'),
    sa.UniqueConstraint('birth_year'),
    sa.UniqueConstraint('gender'),
    sa.UniqueConstraint('gender'),
    sa.UniqueConstraint('height'),
    sa.UniqueConstraint('height'),
    sa.UniqueConstraint('img'),
    sa.UniqueConstraint('img'),
    sa.UniqueConstraint('mass'),
    sa.UniqueConstraint('mass'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('name')
    )
    op.add_column('favorite', sa.Column('Characters_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'favorite', 'characters', ['Characters_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'favorite', type_='foreignkey')
    op.drop_column('favorite', 'Characters_id')
    op.drop_table('characters')
    # ### end Alembic commands ###
